"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import store from './store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[inter.className, 'bg-slate-100'].join(' ')}>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
